title: Philip Daoud
logo: profile.png  # Path to your photo if you have one
description: Software Developer | UI/UX Enthusiast | Open Source Contributor
show_downloads: true
theme: jekyll-architect-theme

